### ISSUE TITLE
'window is not defined' when calling 'await Database.load('sqlite:database.db');'

### ISSUE THREAD

**Issue by ollema** [tauri-apps/tauri-plugin-sql#126]
I can't get this plugin to work, whenever I call e.g.:
`const db = await Database.load('sqlite:database.db');`
I get:
```
window is not defined
ReferenceError: window is not defined
    at o (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:100)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:466
    at new Promise (<anonymous>)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:433
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:2234
    at Object.next (file:///home/s0001325/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:2339)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:1276
    at new Promise (<anonymous>)
    at o (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:1021)
    at r (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:364)
```

doesn't matter if I run `npm run dev` or `npm run tauri dev` - still happens everytime that line is called :(

not sure if this is a bug or if I'm doing something wrong

here is all of my source code:
https://github.com/ollema/mfcl

**Comment by FabianLars** [comment]
With svelte you need to run the code in onMount or a browser env check.
